Transform: AWS::Serverless-2016-10-31

Resources:
    # GetTasks Lambda Function
    - GetTasksFunction:
          Type: AWS::Serverless::Function
          Properties:
            Runtime: python3.11
            CodeUri: src/handlers/getTasks
            Handler: app.lambda_handler
            Policies:
              - DynamoDBCrudPolicy:
                  TableName: !Ref TasksTable
            Environment:
              Variables:
                TASKS_TABLE: !Ref TasksTable
            Events:
              GetTasksFunctionApi:
                Type: Api
                Properties:
                  RestApiId: !Ref TasksApi
                  Path: /tasks
                  Method: GET
                  Auth:
                    Authorizer: MyLambdaTokenAuthorizer
    # Create DynamoDB table
    - TasksTable:
        Type: AWS::DynamoDB::Table
        Properties:
          AttributeDefinitions:
            - AttributeName: "user"
              AttributeType: "S"
            - AttributeName: "id"
              AttributeType: "S"
          KeySchema:
            - AttributeName: "user"
              KeyType: "HASH"
            - AttributeName: "id"
              KeyType: "RANGE"
          BillingMode: PAY_PER_REQUEST










